/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.app.view;

import br.com.ifba.agendaDeVacina.view.TelaAgendaDeVacinas;
import br.com.ifba.usuario.controller.UsuarioIController;

import br.com.ifba.animal.view.AnimalView;
import br.com.ifba.gerenciamentoUsuarios.view.GerenciamentoUsuariosTela01;
import br.com.ifba.lar_temporario.view.LarTemporarioView;
import br.com.ifba.tela.util.ApplicationContextProvider;

import br.com.ifba.campanha.view.TelaCampanha;

import jakarta.annotation.PostConstruct;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;


/**
 *
 * @author Jefferson S
 */
@Component
public class Main extends javax.swing.JFrame {
    
    @Autowired
    private TelaCampanha telaCampanhas;
    @Autowired 
    private UsuarioIController usuarioController;
    @Lazy
    @Autowired
    private GerenciamentoUsuariosTela01 gerenciamentoUsuariosTela01;
    @Autowired
    private TelaAgendaDeVacinas telaAgendaDeVacinas;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    @PostConstruct 
    public void init() {
        // Centraliza a janela na tela
        this.setLocationRelativeTo(null);

        // ActionListeners para cada botão
        btnInque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInqueActionPerformed(evt);
            }
        });
        btnLarTemporarioLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LarTemporarioView tela = ApplicationContextProvider
                    .getApplicationContext()
                    .getBean(LarTemporarioView.class);

                tela.setVisible(true);
            }
        });
        btnRodrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodrigoActionPerformed(evt);
            }
        });
        
        btnJefferson.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
                gerenciamentoUsuariosTela01.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                        // Esta ação será executada quando a tela GerenciamentoUsuariosTela01 for fechada
                        Main.this.setVisible(true);
                    }
                });

                gerenciamentoUsuariosTela01.setVisible(true);
                Main.this.setVisible(false);
            }
        });
        
        btnJeffersonVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaAgendaDeVacinas.setVisible(true);
                //GerenciamentoUsuariosTela01.this.setVisible(false);
            }
        });

        // Configuração de fechamento da janela
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); // Garante que a aplicação feche
    }

    // --- ADICIONAR: Métodos de Ação para os Botões ---
    // Exemplo: Botão Jefferson abre a tela CursoListar
    private void btnJeffersonActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Jefferson");
    }

    private void btnInqueActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Inque");
        
    }

    private void btnLuanActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Luan");
        
    }

    private void btnLuisActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Luis");
        
    }
    
   /* private void btnRodrigoActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Rodrigo");
        
    }
*/
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInque = new javax.swing.JButton();
        btnLarTemporarioLuan = new javax.swing.JButton();
        btnRodrigo = new javax.swing.JButton();
        btnJefferson = new javax.swing.JButton();
<<<<<<< HEAD
        btnJeffersonVacinas = new javax.swing.JButton();
=======
        btnCampanhas = new javax.swing.JButton();
>>>>>>> f50fc5b (feat(campanha): Implementa backend e tela de gerenciamento de campanhas)

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInque.setText("Inque");

        btnLarTemporarioLuan.setText("Lar Temporario (Luan)");
        btnLarTemporarioLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLarTemporarioLuanActionPerformed(evt);
            }
        });

        btnRodrigo.setText("Gerenciamento Animais (Rodrigo)");
        btnRodrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodrigoActionPerformed(evt);
            }
        });

        btnJefferson.setText("Gestão de Usuários (Jefferson)");

<<<<<<< HEAD
        btnJeffersonVacinas.setText("Agenda de Vacinas (Jefferson)");
        btnJeffersonVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJeffersonVacinasActionPerformed(evt);
=======
        btnCampanhas.setText("Campanhas (Luis)");
        btnCampanhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampanhasActionPerformed(evt);
>>>>>>> f50fc5b (feat(campanha): Implementa backend e tela de gerenciamento de campanhas)
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
<<<<<<< HEAD
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJeffersonVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnInque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLarTemporarioLuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRodrigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnJefferson, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
=======
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLarTemporarioLuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRodrigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJefferson, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCampanhas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> f50fc5b (feat(campanha): Implementa backend e tela de gerenciamento de campanhas)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnInque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLarTemporarioLuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCampanhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRodrigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJefferson)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJeffersonVacinas)
                .addContainerGap(27, Short.MAX_VALUE))
=======
                .addContainerGap(68, Short.MAX_VALUE))
>>>>>>> f50fc5b (feat(campanha): Implementa backend e tela de gerenciamento de campanhas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLarTemporarioLuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLarTemporarioLuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLarTemporarioLuanActionPerformed

    private void btnRodrigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRodrigoActionPerformed
           
        AnimalView tela = ApplicationContextProvider
            .getApplicationContext()
            .getBean(AnimalView.class);
        
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        
    }//GEN-LAST:event_btnRodrigoActionPerformed

    private void btnJeffersonVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJeffersonVacinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJeffersonVacinasActionPerformed
    private void btnCampanhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampanhasActionPerformed
        telaCampanhas.setVisible(true);
    }//GEN-LAST:event_btnCampanhasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCampanhas;
    private javax.swing.JButton btnInque;
    private javax.swing.JButton btnJefferson;
    private javax.swing.JButton btnJeffersonVacinas;
    private javax.swing.JButton btnLarTemporarioLuan;
    private javax.swing.JButton btnRodrigo;
    // End of variables declaration//GEN-END:variables
}
