/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.app.view;

import br.com.ifba.animal.view.AnimalView;
import br.com.ifba.lar_temporario.view.LarTemporarioView;
import br.com.ifba.tela.util.ApplicationContextProvider;
import jakarta.annotation.PostConstruct;
import javax.swing.JOptionPane;
import org.springframework.stereotype.Component;

/**
 *
 * @author Jefferson S
 */
@Component
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    @PostConstruct 
    public void init() {
        // Centraliza a janela na tela
        this.setLocationRelativeTo(null);

        // ActionListeners para cada botão
        btnInque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInqueActionPerformed(evt);
            }
        });
        btnLarTemporarioLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LarTemporarioView tela = ApplicationContextProvider
                    .getApplicationContext()
                    .getBean(LarTemporarioView.class);

                tela.setVisible(true);
            }
        });
        btnLuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuisActionPerformed(evt);
            }
        });
        btnRodrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodrigoActionPerformed(evt);
            }
        });
        btnJefferson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJeffersonActionPerformed(evt);
            }
        });

        // Configuração de fechamento da janela
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); // Garante que a aplicação feche
    }

    // --- ADICIONAR: Métodos de Ação para os Botões ---
    // Exemplo: Botão Jefferson abre a tela CursoListar
    private void btnJeffersonActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Jefferson");
    }

    private void btnInqueActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Inque");
        
    }

    private void btnLuanActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Luan");
        
    }

    private void btnLuisActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Funcionalidade do Luis");
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInque = new javax.swing.JButton();
        btnLarTemporarioLuan = new javax.swing.JButton();
        btnLuis = new javax.swing.JButton();
        btnRodrigo = new javax.swing.JButton();
        btnJefferson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInque.setText("Inque");

        btnLarTemporarioLuan.setText("Lar Temporario (Luan)");
        btnLarTemporarioLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLarTemporarioLuanActionPerformed(evt);
            }
        });

        btnLuis.setText("Luis");

        btnRodrigo.setText("Gerenciamento Animais (Rodrigo)");
        btnRodrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodrigoActionPerformed(evt);
            }
        });

        btnJefferson.setText("Jefferson");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLarTemporarioLuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRodrigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJefferson, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnInque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLarTemporarioLuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRodrigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnJefferson)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLarTemporarioLuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLarTemporarioLuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLarTemporarioLuanActionPerformed

    private void btnRodrigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRodrigoActionPerformed
           
        AnimalView tela = ApplicationContextProvider
            .getApplicationContext()
            .getBean(AnimalView.class);
        
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        
    }//GEN-LAST:event_btnRodrigoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInque;
    private javax.swing.JButton btnJefferson;
    private javax.swing.JButton btnLarTemporarioLuan;
    private javax.swing.JButton btnLuis;
    private javax.swing.JButton btnRodrigo;
    // End of variables declaration//GEN-END:variables
}
